platform :ios, '7.0'
pod 'BGUtilities'
pod 'Colours'
pod 'POP+MCAnimate'
pod 'libHN'
pod 'MMDrawerController'
pod 'BMYScrollableNavigationBar'
pod 'TTTAttributedLabel'
pod 'FRDLivelyButton'
pod 'RNGridMenu', :git => 'https://github.com/bennyguitar/RNGridMenu.git'
pod 'MTStatusBarOverlay'
pod 'XLForm'